#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pandas
Version  : 0.22.0
Release  : 48
URL      : http://pypi.debian.net/pandas/pandas-0.22.0.tar.gz
Source0  : http://pypi.debian.net/pandas/pandas-0.22.0.tar.gz
Summary  : Powerful data structures for data analysis, time series,and statistics
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: pandas-python3
Requires: pandas-python
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dateutil
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : pytz
BuildRequires : setuptools

%description
**pandas** is a Python package providing fast, flexible, and expressive data
        structures designed to make working with structured (tabular, multidimensional,
        potentially heterogeneous) and time series data both easy and intuitive. It
        aims to be the fundamental high-level building block for doing practical,
        **real world** data analysis in Python. Additionally, it has the broader goal
        of becoming **the most powerful and flexible open source data analysis /
        manipulation tool available in any language**. It is already well on its way
        toward this goal.

%package python
Summary: python components for the pandas package.
Group: Default
Requires: pandas-python3

%description python
python components for the pandas package.


%package python3
Summary: python3 components for the pandas package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pandas package.


%prep
%setup -q -n pandas-0.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523295735
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
