#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pandas
Version  : 1.2.0
Release  : 92
URL      : https://github.com/pandas-dev/pandas/releases/download/v1.2.0/pandas-1.2.0.tar.gz
Source0  : https://github.com/pandas-dev/pandas/releases/download/v1.2.0/pandas-1.2.0.tar.gz
Summary  : Powerful data structures for data analysis, time series, and statistics
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT Python-2.0
Requires: pandas-license = %{version}-%{release}
Requires: pandas-python = %{version}-%{release}
Requires: pandas-python3 = %{version}-%{release}
Requires: numpy
Requires: python-dateutil
Requires: pytz
BuildRequires : Cython
BuildRequires : buildreq-distutils3
BuildRequires : numpy
BuildRequires : python-dateutil
BuildRequires : pytz

%description
**pandas** is a Python package that provides fast, flexible, and expressive data
        structures designed to make working with structured (tabular, multidimensional,
        potentially heterogeneous) and time series data both easy and intuitive. It
        aims to be the fundamental high-level building block for doing practical,
        **real world** data analysis in Python. Additionally, it has the broader goal
        of becoming **the most powerful and flexible open source data analysis /
        manipulation tool available in any language**. It is already well on its way
        toward this goal.

%package license
Summary: license components for the pandas package.
Group: Default

%description license
license components for the pandas package.


%package python
Summary: python components for the pandas package.
Group: Default
Requires: pandas-python3 = %{version}-%{release}

%description python
python components for the pandas package.


%package python3
Summary: python3 components for the pandas package.
Group: Default
Requires: python3-core
Provides: pypi(pandas)
Requires: pypi(numpy)
Requires: pypi(python_dateutil)
Requires: pypi(pytz)

%description python3
python3 components for the pandas package.


%prep
%setup -q -n pandas-1.2.0
cd %{_builddir}/pandas-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609275512
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pandas
cp %{_builddir}/pandas-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pandas/eadef9b17a3f52c1c8cf3677156a66e818918051
cp %{_builddir}/pandas-1.2.0/LICENSES/DATEUTIL_LICENSE %{buildroot}/usr/share/package-licenses/pandas/59705b5e5de0c08d1506859dab3dd36715998366
cp %{_builddir}/pandas-1.2.0/LICENSES/HAVEN_LICENSE %{buildroot}/usr/share/package-licenses/pandas/9d84be01def522d7ac0016e7ccf20bf0f56c74c4
cp %{_builddir}/pandas-1.2.0/LICENSES/MUSL_LICENSE %{buildroot}/usr/share/package-licenses/pandas/aa79650c58365b839520605049992f3ec72c6589
cp %{_builddir}/pandas-1.2.0/LICENSES/NUMPY_LICENSE %{buildroot}/usr/share/package-licenses/pandas/aae4e68d85be0c9ead6a174a888fa39acbf8a02e
cp %{_builddir}/pandas-1.2.0/LICENSES/PSF_LICENSE %{buildroot}/usr/share/package-licenses/pandas/a6cdff8a5e3b32bfdbe19e3656e0414da538da84
cp %{_builddir}/pandas-1.2.0/LICENSES/SAS7BDAT_LICENSE %{buildroot}/usr/share/package-licenses/pandas/a7ffac8725946811387bca8b7c919865928147b7
cp %{_builddir}/pandas-1.2.0/LICENSES/SCIPY_LICENSE %{buildroot}/usr/share/package-licenses/pandas/b4877732067b3d91fb2e5037d6fb9f7701516eca
cp %{_builddir}/pandas-1.2.0/LICENSES/ULTRAJSON_LICENSE %{buildroot}/usr/share/package-licenses/pandas/d95dab5d75b58d376b7ee30bc0516908f40f4dc3
cp %{_builddir}/pandas-1.2.0/LICENSES/XARRAY_LICENSE %{buildroot}/usr/share/package-licenses/pandas/61e6a9463669164753f1dbf0692469e454760a57
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pandas/59705b5e5de0c08d1506859dab3dd36715998366
/usr/share/package-licenses/pandas/61e6a9463669164753f1dbf0692469e454760a57
/usr/share/package-licenses/pandas/9d84be01def522d7ac0016e7ccf20bf0f56c74c4
/usr/share/package-licenses/pandas/a6cdff8a5e3b32bfdbe19e3656e0414da538da84
/usr/share/package-licenses/pandas/a7ffac8725946811387bca8b7c919865928147b7
/usr/share/package-licenses/pandas/aa79650c58365b839520605049992f3ec72c6589
/usr/share/package-licenses/pandas/aae4e68d85be0c9ead6a174a888fa39acbf8a02e
/usr/share/package-licenses/pandas/b4877732067b3d91fb2e5037d6fb9f7701516eca
/usr/share/package-licenses/pandas/d95dab5d75b58d376b7ee30bc0516908f40f4dc3
/usr/share/package-licenses/pandas/eadef9b17a3f52c1c8cf3677156a66e818918051

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
