#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pandas
Version  : 0.19.2
Release  : 30
URL      : http://pypi.debian.net/pandas/pandas-0.19.2.tar.gz
Source0  : http://pypi.debian.net/pandas/pandas-0.19.2.tar.gz
Summary  : Powerful data structures for data analysis, time series,and statistics
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear
Requires: pandas-python
BuildRequires : numpy-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
.. _contributing.docs:
Contributing to the documentation
=================================

%package python
Summary: python components for the pandas package.
Group: Default

%description python
python components for the pandas package.


%prep
%setup -q -n pandas-0.19.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485731743
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1485731743
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
